import hashlib
from pathlib import Path

import yaml


def test_line_comparisons_require_identical_fixture_hashes(tmp_path):
    import json
    import runpy

    import pytest

    helper = runpy.run_path(str(Path(__file__).parents[1] / "scripts/analyze_model_data_r2.py"))
    baseline = tmp_path / "baseline"
    for alias, digest in (("q35-p12", "a" * 64), ("challenger", "b" * 64)):
        folder = baseline / alias / "line"
        folder.mkdir(parents=True)
        (folder / "summary.json").write_text(
            json.dumps({"total": 180, "suite_sha256": digest, "metadata": {}})
        )
        (folder / "results.jsonl").write_text(
            "".join(
                json.dumps(
                    {
                        "case_id": str(i),
                        "exact": True,
                        "syntax": "pass",
                        "finish_reason": "eos",
                        "fallback_cap": False,
                        "latency_seconds": 1.0,
                        "longest_exact_character_prefix": 1,
                        "returned_characters": 1,
                        "returned_bytes": 1,
                        "output_tokens": 1,
                        "language": "python",
                    }
                )
                + "\n"
                for i in range(180)
            )
        )
    with pytest.raises(ValueError, match="different line fixtures"):
        helper["compare_lines"](baseline, tmp_path)


def test_rendered_kaggle_workers_are_valid_python():
    import ast
    import json

    root = Path(__file__).parents[1]
    for name in ("run_evaluation.py", "run_context.py", "run_pilot.py"):
        source = (root / "kaggle/model_data_r2" / name).read_text()
        rendered = source.replace(
            "__PILOT_EXPECTED__",
            json.dumps({"R2_STANDARD": "a" * 64, "R2_FILTERED": "b" * 64}),
        ).replace("__CHECKOUT_COMMIT__", "1" * 40)
        ast.parse(rendered)


def test_local_probe_refuses_listener_and_context_includes_output():
    import runpy
    import socket

    import pytest

    helper = runpy.run_path(str(Path(__file__).parents[1] / "scripts/measure_r2_local.py"))
    with socket.socket() as listener:
        listener.bind(("127.0.0.1", 0))
        listener.listen()
        port = listener.getsockname()[1]
        with pytest.raises(OSError):
            helper["verify_unused_port"](port)
    helper["verify_unused_port"](port)
    helper["verify_context_budget"]("q25-coder", 32736)
    with pytest.raises(ValueError):
        helper["verify_context_budget"]("q25-coder", 32737)


def test_registered_r2_budget_and_shared_treatment_settings():
    root = Path(__file__).parents[1]
    config = yaml.safe_load((root / "configs/research/model_data_r2.yaml").read_text())
    train = config["training"]
    assert train["successful_updates"] * train["tokens_per_update"] == 5_013_504
    assert train["parent"] == "q35-p12"
    assert 2 * 5_013_504 + (6 + 16) * 32768 < config["limits"]["additional_training_input_tokens"]
    assert config["evaluation"]["causal"]["max_new_tokens"] == 96
    assert config["limits"]["simultaneous_gpu_allocations"] == 1
    assert config["selection"]["deployed_model_replacement"] == "forbidden"
    assert config["long_context"]["gpu_wall_seconds"] == 3600


def test_multiline_comment_is_not_a_line_target():
    from tinycomplete.code_cpt.model_data_r2 import line_candidate

    content = "/*\nthis is a comment without a leading star\n*/\nint meaning = 123456;\n"
    record = {
        "content": content,
        "parse_status": "pass",
        "language": "c",
        "content_sha256": hashlib.sha256(content.encode()).hexdigest(),
        "repository": "synthetic/control",
        "repository_aliases": ["synthetic/control"],
        "path": "control.c",
    }
    case = line_candidate(record)
    assert case["line_number"] == 4
    assert case["source_before"] + case["reference"] + case["source_after"] == content
    assert case["prompt"] == case["source_before"]


def test_line_fixture_excludes_generated_sources_without_changing_training_policy():
    from tinycomplete.code_cpt.model_data_r2 import line_source_rejection

    assert line_source_rejection(
        {"path": "html/search/files_0.js", "content": "var searchData=[];"}
    )
    assert line_source_rejection(
        {"path": "data.h", "content": "char blob[] = {" + "0x61," * 64 + "};"}
    )
    assert line_source_rejection(
        {"path": "src/example.py", "content": "# Automatically generated\nx = 123"}
    )
    assert line_source_rejection({"path": "src/answer.c", "content": "int answer = 0x61;"}) is None
    assert line_source_rejection(
        {"path": "parser.js", "content": "// Generated from grammar by ANTLR"}
    )
    assert line_source_rejection(
        {"path": "ffi.java", "content": "// File was autogenerated by JNAerator"}
    )
    assert line_source_rejection({"path": "rpc.grpc.pb.cc", "content": "int placeholder;"})


def test_near_duplicates_and_repository_cap():
    from collections import Counter

    from tinycomplete.code_cpt.model_data_r2 import NearDuplicates, filtered_reason

    near = NearDuplicates()
    assert not near.check_and_add("def addition(a, b):\n    return a + b\n")
    assert near.check_and_add("def addition(a, b):\n  return a + b\n")
    record = {
        "content": "int x = 1;",
        "path": "code.c",
        "content_sha256": "x",
        "tokens": [1] * 20,
        "parse_status": "pass",
        "repository": "public/repo",
    }
    assert filtered_reason(record, NearDuplicates(), set(), Counter(), 1000) == (
        "repository_token_cap"
    )


def test_explicit_campaign_survives_prediction_resume(tmp_path):
    import json

    from tinycomplete.observability.context import ensure_persistent_run_identity

    path = tmp_path / "run.json"
    metadata = {"campaign_id": "synthetic-r2", "suite_sha256": "fixed"}
    first = ensure_persistent_run_identity(path, metadata)
    path.write_text(json.dumps(first.metadata))
    second = ensure_persistent_run_identity(path, metadata)
    assert first.context.campaign_id == second.context.campaign_id == "synthetic-r2"
    assert first.context.run_id == second.context.run_id
    assert first.context.run_attempt_id != second.context.run_attempt_id


def test_restart_gate_ignores_io_wait_but_not_consumed_data():
    import json

    from tinycomplete.code_cpt.resume_compare import numerical_restart_gate

    historical = json.loads(
        (Path(__file__).parents[1] / "reports/code_cpt/research_r1/resume_test.json").read_text()
    )
    comparison = historical["state_comparison"]
    differences = historical["loss_absolute_differences"]
    assert numerical_restart_gate(comparison, differences)
    comparison["ranks"][0]["metadata_b"]["next_block"] += 1
    assert not numerical_restart_gate(comparison, differences)


def test_incremental_line_stop_preserves_raw_whitespace_and_default_generation(monkeypatch):
    import torch

    from tinycomplete.eval.code_generation import TransformersGenerationProvider

    monkeypatch.delenv("TABCOMPLETE_OBSERVABILITY_ENABLED", raising=False)

    class Tokenizer:
        eos_token_id = 0

        def __call__(self, prompt, **kwargs):
            return {"input_ids": torch.tensor([[ord(c) for c in prompt]])}

        def decode(self, ids, **kwargs):
            return "".join(chr(int(i)) for i in ids)

    class Model:
        def generate(self, input_ids, **kwargs):
            assert kwargs["do_sample"] is False and kwargs["max_new_tokens"] == 96
            output = input_ids
            for character in "  kept\nextra":
                output = torch.cat((output, torch.tensor([[ord(character)]])), dim=1)
                stopping = kwargs.get("stopping_criteria")
                if stopping is not None and stopping(output, None).all():
                    break
            return output

    provider = TransformersGenerationProvider.__new__(TransformersGenerationProvider)
    provider.model, provider.tokenizer = Model(), Tokenizer()
    provider.torch, provider.device = torch, torch.device("cpu")
    result = provider.generate_line_detailed("prefix", 96)
    assert result.text == "  kept\n" and result.finish_reason == "newline"
    assert result.first_output_ms is not None
    ordinary = provider.generate_detailed("prefix", 96)
    assert ordinary.text == "  kept\nextra"
    assert ordinary.first_output_ms is None


def test_empty_captured_response_upload_is_an_explicit_stream(tmp_path, monkeypatch):
    import httpx

    from tinycomplete.observability.artifacts import ArtifactStore, sync_artifacts

    store = ArtifactStore(tmp_path / "cas")
    store.capture_text("model-output", "", authorized=True)
    token = tmp_path / "token"
    token.write_text("synthetic-upload-token")
    monkeypatch.setenv("TABCOMPLETE_ARTIFACT_UPLOAD_URL", "http://fixture.invalid")
    monkeypatch.setenv("TABCOMPLETE_ARTIFACT_UPLOAD_TOKEN_FILE", str(token))

    def put(self, url, **kwargs):
        assert not isinstance(kwargs["content"], bytes)
        assert b"".join(kwargs["content"]) == b""
        return httpx.Response(201, request=httpx.Request("PUT", url))

    monkeypatch.setattr(httpx.Client, "put", put)
    assert sync_artifacts(store.root) == {"accepted": 1, "failed": 0}


def test_first_line_removes_crlf_not_meaningful_whitespace():
    from tinycomplete.eval.code_generation import returned_first_line

    assert returned_first_line("  kept  \r\nnext") == "  kept  "
    assert returned_first_line("  kept  \nnext") == "  kept  "
    assert returned_first_line("  kept  ") == "  kept  "
    assert returned_first_line("trailing CR without LF\r") == "trailing CR without LF\r"


def test_native_line_stop_omission_uses_observed_terminator_not_gold():
    import runpy

    helper = runpy.run_path(str(Path(__file__).parents[1] / "scripts/evaluate_causal_line.py"))
    case = {
        "id": "synthetic",
        "language": "python",
        "repository": "fixture",
        "source_before": "value =",
        "source_after": "\n",
        "reference": " 1  ",
        "source_sha256": "fixture",
    }
    result = helper["score_line"](case, " 1  \r", native_newline_omitted=True)
    assert result["exact"] and result["raw_response"] == " 1  \r"
    unchanged = helper["score_line"](case, " 1  \r", native_newline_omitted=False)
    assert not unchanged["exact"]


def test_telemetry_ids_do_not_consume_or_replay_training_random_state():
    import random

    from tinycomplete.observability.bootstrap import ResearchSafeIdGenerator

    before = random.getstate()
    generator = ResearchSafeIdGenerator()
    first = (generator.generate_trace_id(), generator.generate_span_id())
    assert random.getstate() == before
    random.setstate(before)
    second = (generator.generate_trace_id(), generator.generate_span_id())
    assert first != second
    assert random.getstate() == before
    assert all(first) and all(second)


def test_container_timeout_removes_only_its_unique_disposable_container(tmp_path, monkeypatch):
    import subprocess

    from tinycomplete.eval import code_benchmark as module

    commands = []
    monkeypatch.setattr(module, "_container_runtime", lambda: "podman")

    def command(args, **kwargs):
        commands.append(args)
        return subprocess.CompletedProcess(args, 0)

    def timed_out(args, *positional, **kwargs):
        commands.append(args)
        return module.CheckResult(status="timeout")

    monkeypatch.setattr(module.subprocess, "run", command)
    monkeypatch.setattr(module, "_run_trusted", timed_out)
    result = module._run_container(["python3", "fixture.py"], tmp_path, 0.1, "fixture:1")
    assert result.status == "timeout"
    launched = commands[1]
    name = launched[launched.index("--name") + 1]
    assert name.startswith("tabcomplete-case-")
    assert "--network=none" in launched
    assert commands[2] == ["podman", "rm", "--force", name]


def test_pilot_baseline_preserves_production_trainer_json_contract(tmp_path):
    import json
    import runpy

    root = Path(__file__).parents[1]
    worker = runpy.run_path(str(root / "kaggle/model_data_r2/run_pilot.py"), run_name="test")
    source = (
        root / "reports/code_cpt/research_r1/campaign_metrics/parents/P12/fresh_development.json"
    )
    destination = tmp_path / "baseline.json"
    worker["save_training_baseline"](source, destination)
    assert json.loads(destination.read_text())["metrics"]["overall_code"]["nll"] > 0
