"""Install the selected local LazyVim predictor without replacing mappings."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "tools/trajectory_collector/nvim"
DEFAULT_RUNTIME = ROOT.parent / "tabcomplete/outputs/tools/llama.cpp/build/bin/llama-server"


def sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def owned_by_nix(path: Path) -> bool:
    if path.is_symlink() or str(path.resolve()).startswith("/nix/store/"):
        return True
    if path.exists():
        head = path.read_text()[:512].lower()
        return "home-manager" in head or "generated by nix" in head
    return False


def render_config(
    original: str,
    *,
    model_revision: str,
    model_alias: str,
    runtime_config_hash: str,
    experimental_automatic: bool,
) -> str:
    match = re.search(
        r'(?m)^(\s*dir\s*=\s*)"[^"]*/tools/trajectory_collector/nvim"(,\s*)$', original
    )
    if not match:
        raise ValueError("existing LazyVim trajectory plugin dir was not found exactly once")
    if len(re.findall(r"tools/trajectory_collector/nvim", original)) != 1:
        raise ValueError("ambiguous trajectory plugin configuration")
    replacement = match.group(1) + '"' + str(PLUGIN) + '"' + match.group(2)
    updated = original[: match.start()] + replacement + original[match.end() :]
    needle = 'require("tabcomplete_trajectory").setup({'
    if needle not in updated:
        raise ValueError("collector setup call not found")
    mode = "automatic" if experimental_automatic else "manual"
    line = (
        '\n      require("tabcomplete_trajectory.predict").setup({ '
        f'model = "{model_alias}", model_revision = "{model_revision}", '
        'precision = "Q4_K_M", adapter_identity = "full-weight", '
        f'runtime_config_hash = "{runtime_config_hash}", '
        f'mode = "{mode}", experimental_auto_opt_in = '
        f"{str(experimental_automatic).lower()}, automatic_quality_validated = false, "
        "automatic_personalization_enabled = false, persist_mode = true })"
    )
    if 'require("tabcomplete_trajectory.predict").setup' in updated:
        updated = re.sub(
            r'\n\s*require\("tabcomplete_trajectory.predict"\)\.setup\(\{[^\n]*\}\)',
            line,
            updated,
            count=1,
        )
    else:
        # Insert after the collector setup's closing line. Preserve all other
        # settings and existing mappings byte-for-byte.
        close = updated.find("\n      })", updated.index(needle))
        if close < 0:
            raise ValueError("collector setup closing line not found")
        close += len("\n      })")
        updated = updated[:close] + line + updated[close:]
    return updated


def render_service(model: Path, runtime: Path) -> str:
    for path in (model, runtime):
        if any(char.isspace() for char in str(path)):
            raise ValueError("service paths must not contain whitespace")
    return (
        "[Unit]\nDescription=TabComplete local next-edit predictor\n"
        "After=network.target\n\n[Service]\nType=simple\n"
        f"ExecStart={runtime} -m {model} --host 127.0.0.1 --port 19093 "
        "-t 4 -tb 4 -ngl 0 -c 2304 -b 256 -ub 64 -np 1 "
        "--cache-ram 128 --ctx-checkpoints 32 --no-cache-idle-slots --no-warmup\n"
        "Restart=on-failure\nRestartSec=3\nNoNewPrivileges=yes\n"
        "MemoryMax=1500M\n\n[Install]\nWantedBy=default.target\n"
    )


def install(
    config: Path,
    unit: Path,
    model: Path,
    runtime: Path,
    expected_sha: str,
    model_alias: str,
    *,
    dry_run: bool,
    experimental_automatic: bool = False,
) -> dict:
    if owned_by_nix(config) or owned_by_nix(unit):
        raise RuntimeError("Nix/Home Manager owns this path; edit its source configuration")
    if not model.is_file() or sha(model) != expected_sha:
        raise ValueError("selected model artifact hash mismatch")
    if model.stat().st_size != 397_807_232:
        raise ValueError("selected model artifact size mismatch")
    if not runtime.is_file():
        raise FileNotFoundError(runtime)
    original = config.read_text()
    service = render_service(model.resolve(), runtime.resolve())
    runtime_config_hash = hashlib.sha256(service.encode()).hexdigest()
    updated = render_config(
        original,
        model_revision=expected_sha,
        model_alias=model_alias,
        runtime_config_hash=runtime_config_hash,
        experimental_automatic=experimental_automatic,
    )
    if dry_run:
        return {
            "config": str(config),
            "unit": str(unit),
            "model_sha256": expected_sha,
            "mode": "automatic" if experimental_automatic else "manual",
            "runtime_config_hash": runtime_config_hash,
            "dry_run": True,
        }
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    backup = config.with_name(config.name + ".backup-" + stamp)
    backup.write_text(original)
    prior_unit = unit.read_text() if unit.exists() else None
    unit_backup = unit.with_name(unit.name + ".backup-" + stamp) if prior_unit else None
    if unit_backup and prior_unit:
        unit_backup.write_text(prior_unit)
    config.write_text(updated)
    unit.parent.mkdir(parents=True, exist_ok=True)
    unit.write_text(service)
    try:
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True, capture_output=True)
        subprocess.run(
            ["systemctl", "--user", "enable", "--now", unit.name], check=True, capture_output=True
        )
        if prior_unit != service:
            subprocess.run(
                ["systemctl", "--user", "restart", unit.name], check=True, capture_output=True
            )
    except (OSError, subprocess.CalledProcessError):
        config.write_text(original)
        if prior_unit is None:
            unit.unlink(missing_ok=True)
        else:
            unit.write_text(prior_unit)
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=False, capture_output=True)
        raise RuntimeError(
            "local predictor service failed to start; installer restored configuration"
        ) from None
    return {
        "config": str(config),
        "backup": str(backup),
        "unit_backup": str(unit_backup) if unit_backup else None,
        "unit": str(unit),
        "model_sha256": expected_sha,
        "mode": "automatic" if experimental_automatic else "manual",
        "runtime_config_hash": runtime_config_hash,
        "dry_run": False,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--runtime", type=Path, default=DEFAULT_RUNTIME)
    parser.add_argument("--model-sha256", required=True)
    parser.add_argument("--model-alias", required=True)
    parser.add_argument("--experimental-automatic", action="store_true")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path.home() / ".config/nvim/lua/plugins/tabcomplete-trajectory.lua",
    )
    parser.add_argument(
        "--unit",
        type=Path,
        default=Path.home() / ".config/systemd/user/tabcomplete-predictor.service",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    result = install(
        args.config,
        args.unit,
        args.model,
        args.runtime,
        args.model_sha256,
        args.model_alias,
        dry_run=args.dry_run,
        experimental_automatic=args.experimental_automatic,
    )
    print(result)


if __name__ == "__main__":
    main()
